spring:
  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ddd
            client-secret: ddd
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  issuer: dnjswns648@naver.com
  secret_key: test_key
